# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-17 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='operationlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redisname', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=20)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='redisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redisname', models.CharField(max_length=10)),
                ('redistype', models.CharField(choices=[('Sentinel', 'Sentinel'), ('Cluster', 'Cluster'), ('Single', 'Single')], default=2, max_length=10)),
                ('mastername', models.CharField(default='', max_length=20)),
                ('nodelist', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('projectname', models.CharField(max_length=20)),
                ('director', models.CharField(blank=True, max_length=10, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userpermission', models.CharField(blank=True, max_length=100, null=True)),
                ('belong_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
